[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "flask-sqlalchemy",
    "flask-cors",
    "werkzeug",
    "python-dotenv",
    "pillow", 
    "requests",
    "google-genai"
]
